language: node_js
node_js:
  - 12

branches:
  only:
    - master

before_script:
  - npm install

script:
  - CI=false npm run build

production-deploy:
  stage: deploy
  script:
    - ~/dotols/deploy/deploy.sh